### ISSUE TITLE
Add ability to execute visual selections and motions

### ISSUE THREAD

**Issue by bw-matthew** [matthewfranglen/vim-repl#3]
Multiline commands are supported on most shells, and they make a lot of sense in Vim. It would be great if the Repl was able to execute visual selections as commands, even if they span multiple lines. It would also be great to be able to combine the repl command with a motion to execute all of the text covered by the motion.

**Comment by matthewfranglen** [comment]
Fixed in https://github.com/matthewfranglen/vim-repl/commit/f948df3f134d999832f93b121a90bab1cfb20225
